# Generated by Django 5.2.12 on 2026-03-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('project', '0001_initial'), ('project', '0003_preference'), ('project', '0002_assignment'), ('project', '0004_merge_0002_assignment_0003_preference'), ('project', '0005_preference_unique_student_project'),
                ('project', '0006_remove_preference_unique_student_project_and_more'), ('project', '0007_remove_preference_id_alter_preference_slug'), ('project', '0008_rename_slug_preference_id')]

    initial = True

    # dependencies = [
    #     ('user', '0001_initial'),
    #     ('user', '0002_student'),
    #     ('user', '0007_alter_sponsor_phone_number'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('CNCL', 'Cancelled'),
                 ('CMPL', 'Complete'), ('PNDG', 'Pending')], default='PNDG', max_length=4)),
                ('website', models.TextField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.PositiveIntegerField()),
                ('person_type', models.CharField(choices=[
                 ('sponsor', 'Sponsor'), ('student', 'Student')], max_length=10)),
                ('semester', models.CharField(choices=[('fall', 'Fall'),
                 ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='assignments', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('id', models.SlugField(editable=False, max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'project'), name='unique_student_project_preference')],
            },
        ),
    ]
