# Generated by Django 5.2.12 on 2026-03-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_squashed_0008_rename_slug_preference_id'),
        ('user', '0008_alter_student_cwid'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='preference',
            name='unique_student_project_preference',
            constraint=models.UniqueConstraint(fields=('student', 'project'), name='unique_student_project_preference', violation_error_message='This user already has a preference for this project (Try updating instead)'),
        ),
    ]
