# Generated by Django 5.2.12 on 2026-03-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_preference_unique_student_project_preference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preference',
            name='unique_student_project_preference',
        ),
    ]
