# Generated by Django 5.2.12 on 2026-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_assignment_updated_at_preference_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
