# Generated by Django 5.2.12 on 2026-03-18 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_website'),
        ('user', '0013_remove_student_semester_remove_student_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='person_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='year',
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.SlugField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('year', models.PositiveIntegerField(help_text='Enter a four-digit year between 1900 and the current year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('assignment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(to='project.project')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.semester'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('semester', 'year'), name='unique_semester_year'),
        ),
    ]
