# Generated by Django 5.2.12 on 2026-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_assignment_person_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsor_availability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
