# Generated by Django 5.2.12 on 2026-04-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_sponsor_availability'),
        ('user', '0013_remove_student_semester_remove_student_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sponsor')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
