# Generated by Django 5.2.12 on 2026-04-06 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_feedback'),
        ('user', '0013_remove_student_semester_remove_student_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveIntegerField(help_text='Enter a four-digit year between 1900 and the current or next year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
