# Generated by Django 5.2.12 on 2026-04-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_feedback_semester_alter_assignment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.semester'),
        ),
    ]
