# Generated by Django 5.2.13 on 2026-04-07 15:57

import django.db.models.deletion
import project.models
import project.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_preference_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=project.storage.S3MediaStorage(), upload_to=project.models.attachment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
