# Generated by Django 5.2.13 on 2026-04-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_preference_semester'),
        ('user', '0013_remove_student_semester_remove_student_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'sponsor'), name='unique_name_sponsor'),
        ),
    ]
