# Generated by Django 5.2.13 on 2026-04-07 16:41

import django.core.validators
import project.models
import project.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=project.storage.S3MediaStorage(), upload_to=project.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'png', 'jpeg']), project.models.validate_attachment_file_size]),
        ),
    ]
