# Generated by Django 5.2.13 on 2026-04-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_project_unique_name_sponsor'),
        ('project', '0019_attachment_link_alter_attachment_file'),
    ]

    operations = [
    ]
