# Generated by Django 5.2.13 on 2026-04-13 21:16

import django.core.validators
import django.db.models.deletion
import project.models
import project.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_merge_20260410_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=project.storage.S3MediaStorage(), upload_to=project.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'png', 'jpeg', 'jpg', 'zip']), project.models.validate_attachment_file_size]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
