# Generated by Django 5.2.10 on 2026-02-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('CNCL', 'Cancelled'), ('CMPL', 'Complete'), ('PNDG', 'Pending')], default='PNDG', max_length=4)),
                ('website', models.TextField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sponsor')),
            ],
        ),
    ]
