# Generated by Django 5.2.11 on 2026-02-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_assignment'),
        ('project', '0003_preference'),
    ]

    operations = [
    ]
