# Generated by Django 5.2.12 on 2026-03-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_merge_0002_assignment_0003_preference'),
        ('user', '0007_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('student', 'project'), name='unique_student_project'),
        ),
    ]
