# Generated by Django 5.2.12 on 2026-03-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_preference_unique_student_project'),
        ('user', '0007_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preference',
            name='unique_student_project',
        ),
        migrations.AddField(
            model_name='preference',
            name='slug',
            field=models.CharField(default=None, editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('student', 'project'), name='unique_student_project_preference'),
        ),
    ]
