# Generated by Django 5.2.12 on 2026-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_preference_unique_student_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='id',
        ),
        migrations.AlterField(
            model_name='preference',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
