# Generated by Django 5.2.12 on 2026-03-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_preference_id_alter_preference_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='slug',
            new_name='id',
        ),
    ]
