# Generated by Django 5.2.12 on 2026-03-05 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0007_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cwid',
            field=models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='CWID must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
