# Generated by Django 5.2.12 on 2026-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sponsor_updated_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='projects_allowed',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_code',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=9, null=True),
        ),
    ]
