# Generated by Django 5.2.12 on 2026-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_sponsor_projects_allowed_student_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('Fall', 'fall'), ('Spring', 'spring'), ('Summer', 'summer')], max_length=10, null=True),
        ),
    ]
