# Generated by Django 5.2.12 on 2026-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_code',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=9, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='major'),
        ),
    ]
