# Generated by Django 5.2.11 on 2026-02-13 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cwid',
            field=models.CharField(db_index=True, default=12345678, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='CWID must be exactly 8 digits.', regex='^\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
