# Generated by Django 5.2.11 on 2026-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_cwid_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
